version: '3.4'

services:
  pgsql:
    container_name: pgsql
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tetradka_local
    ports:
      - 15432:5432
    volumes:
      - ${PGSQL_FOLDER}:/var/lib/postgresql/data
      - ${PGSQL_DUMP_FOLDER}:/home/dump

  mariadb:
    container_name: mariadb
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MARIA_ROOT_PASSWORD: password
    ports:
      - 15433:3306
    volumes:
      - ${MARIA_FOLDER}:/var/lib/mysql
      - ${MARIA_DUMP_FOLDER}:/home/dump

  php-fpm:
    container_name: php-fpm
    restart: always
    build:
      context: ./php-fpm
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
    depends_on:
      - pgsql
      - mariadb
    volumes:
      - ${PROJECTS_FOLDER}:/var/www
    extra_hosts:
      outside: 172.17.0.1

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
    volumes:
      - ${PROJECTS_FOLDER}:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"


